#Do not add universalID or any array attributes to this file. They are handled specially

email:email
firstName:firstName
lastName:lastName
homeEmail:secondEmail
middleName:initials
academicLevel:academicLevel
classStanding:classStanding
eduPersonAffiliation:eduPersonAffiliation
