#oktaURL = https://sio-admin.oktapreview.com
#token = REDACTED_OKTA_TOKEN
#inputFilePath = /Users/jcombs/Documents/Clients/Stevens/NonEmpProv/TEST_wd_student_profiles.csv
#logPath = /Users/jcombs/Documents/Clients/Stevens/NonEmpProv/
#threads = 1

oktaURL = https://siot.okta.com
token = REDACTED_OKTA_TOKEN
inputFilePath = /Users/jcombs/Documents/Clients/Stevens/NonEmpProv/test1.csv
logPath = /Users/jcombs/Documents/Clients/Stevens/NonEmpProv/logs/
threads = 1


